import type { Metadata } from "next"
import Link from "next/link"

import { Button } from "@/components/ui/button"
import { SectionHeading } from "@/components/tools/content/section-heading"
import { siteConfig, ogImage } from "@/lib/site"

const title = "Disclaimer — CleanTextly"
const description =
  "Read the Disclaimer covering the limits, accuracy, and intended use of CleanTextly's free browser-based text tools."

export const metadata: Metadata = {
  title,
  description,
  alternates: {
    canonical: "/disclaimer",
  },
  openGraph: {
    title,
    description,
    url: "/disclaimer",
    siteName: siteConfig.name,
    type: "website",
    images: [ogImage],
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: [ogImage.url],
  },
}

const effectiveDate = new Date().toLocaleDateString("en-US", {
  year: "numeric",
  month: "long",
  day: "numeric",
})

export default function DisclaimerPage() {
  return (
    <main className="flex flex-1 flex-col bg-background">
      <section className="mx-auto max-w-3xl px-4 py-24 text-center sm:py-32">
        <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl md:text-6xl">
          Disclaimer
        </h1>

        <p className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground">
          Please read this Disclaimer carefully before using CleanTextly.
        </p>

        <p className="mt-6 text-sm text-muted-foreground">
          Effective Date: <span className="font-medium text-foreground">{effectiveDate}</span>
        </p>
      </section>

      <section className="w-full border-t border-border py-16 sm:py-20">
        <article className="mx-auto flex max-w-3xl flex-col gap-14 px-4">
          <div>
            <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              General Information
            </h2>
            <p className="mt-4 text-muted-foreground">
              CleanTextly (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;)
              provides free online text utilities, such as duplicate line
              removal, JSON formatting, case conversion, text sorting, CSV to
              JSON conversion, and word counting. The information and tool
              outputs provided through this website are for general
              informational purposes only. We make no guarantees regarding
              the completeness, accuracy, reliability, or suitability of any
              output for every possible use case.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              Tool Results
            </h2>
            <p className="mt-4 text-muted-foreground">
              Results produced by CleanTextly&apos;s tools are generated
              automatically based on the input you provide. You should always
              review important results before relying on them. CleanTextly is
              not responsible for decisions made, or actions taken, based on
              output generated by our tools.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              No Professional Advice
            </h2>
            <p className="mt-4 text-muted-foreground">
              CleanTextly does not provide legal, financial, medical, or other
              professional consulting advice. Nothing on this website should
              be treated as a substitute for advice from a qualified
              professional. Please consult an appropriately qualified
              professional for guidance specific to your situation.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              Availability
            </h2>
            <p className="mt-4 text-muted-foreground">
              We may change our services at any time and without notice.
              Features may be added, removed, or updated, and temporary
              downtime may occur due to maintenance or technical issues.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              External Links
            </h2>
            <p className="mt-4 text-muted-foreground">
              This website may contain links to external, third-party
              websites. We do not control and are not responsible for the
              content, accuracy, or privacy practices of any linked
              third-party sites.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              Limitation of Liability
            </h2>
            <p className="mt-4 text-muted-foreground">
              CleanTextly is not liable for any damages or losses arising from
              your use of this website or reliance on any generated tool
              results. The website and its tools are used at your own
              discretion and risk.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              Contact
            </h2>
            <p className="mt-4 text-muted-foreground">
              If you have any questions about this Disclaimer, please reach
              out to us at{" "}
              <a
                href="mailto:contact@cleantextly.com"
                className="text-primary underline-offset-4 hover:underline"
              >
                contact@cleantextly.com
              </a>
              .
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              Updates
            </h2>
            <p className="mt-4 text-muted-foreground">
              We may update this Disclaimer from time to time. When we do, we
              will revise the Effective Date at the top of this page.
            </p>
          </div>
        </article>
      </section>

      <section aria-labelledby="disclaimer-cta-heading" className="w-full border-t border-border bg-muted/30 py-20 sm:py-28">
        <div className="mx-auto max-w-5xl px-4">
          <SectionHeading
            id="disclaimer-cta-heading"
            title="Have Questions About This Disclaimer?"
            description="We're happy to answer any questions about how CleanTextly's tools should be used."
          />

          <div className="mt-8 flex justify-center">
            <Button render={<Link href="/contact" />} nativeButton={false} size="lg">
              Contact Us
            </Button>
          </div>
        </div>
      </section>
    </main>
  )
}
